server:
  port: 8080

spring:
  application.name: backend-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            Path=/eureka/web
          filters:
            SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: panda-service
          uri: lb://panda-service
          predicates:
            - Path=/api/panda/**
          filters:
        #            - AuthenticationFilter

        - id: telbot-service
          uri: lb://telbot-service
          predicates:
            - Path=/api/i113/telegrambot/**

        - id: bornlist-service
          uri: lb://bornlist-service
          predicates:
            - Path=/api/i113/**
          filters:
  #            - AuthenticationFilter
  security:
    oauth2:
      client:
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: x55yAjg31mnrW8Gq9iHEjdnNqV68nnCI
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/"
            scope: openid #message.read
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8081/realms/i113_realm

#Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
