server:
  port: 8080

spring:
  application.name: backend-gateway
  cloud:
    gateway:
      routes:
        - id: panda-service
          uri: lb://panda-service
          predicates:
            - Path=/api/panda/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: x55yAjg31mnrW8Gq9iHEjdnNqV68nnCI
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/"
            scope: openid #message.read
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8081/realms/i113_realm

#Enable these to debug the Authorization flow
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
